# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            NCPA Competition Union
description:      '<blockquote id="slogan">Work hard, then crash everyone <br> 努力，然后干碎所有人</blockquote>'
baseurl:          /

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

collections:
  competitions:
    output: true
  pages:
    output: true